export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    sendOtp: '/auth/sendotp',
    sendOtpRegister: '/auth/sendotpregister',
    verifyOtp: '/auth/verifyotp',
  },
  health: {
    check: '/health-check',
  },
  user: {
    list: '/user',
    create: '/user',
    register: '/user/register',
    update: '/user/update',
    delete: (id: string | number) => `/user/${id}`,
    byId: (id: string | number) => `/user/${id}`,
  },
  role: {
    list: '/role',
    create: '/role',
    byId: (id: string | number) => `/role/${id}`,
    update: (id: string | number) => `/role/${id}`,
    delete: (id: string | number) => `/role/${id}`,
  },
  permission: {
    list: '/permissions',
  },
  brand: {
    list: '/brands',
    create: '/brands',
    update: (id: string | number) => `/brands/update/${id}`,
    byId: (id: string | number) => `/brands/${id}`,
    delete: (id: string | number) => `/brands/${id}`,
  },
  category: {
    list: '/categories',
    tree: '/categories/tree',
    create: '/categories',
    byId: (id: string | number) => `/categories/${id}`,
    bySlug: (slug: string) => `/categories/by-slug/${slug}`,
    deleted: '/categories/deleted',
    update: (id: string | number) => `/categories/${id}`,
    delete: (id: string | number) => `/categories/${id}`,
    deactivate: (id: string | number) => `/categories/${id}/deactivate`,
    status: (id: string | number) => `/categories/${id}/status`,
    move: (id: string | number) => `/categories/${id}/move`,
    reorder: '/categories/reorder',
    merge: '/categories/merge',
  },
  product: {
    list: '/products',
    create: '/products',
    byId: (id: string | number) => `/products/${id}`,
  },
  attribute: {
    list: '/attributes',
    create: '/attributes',
    byId: (id: string | number) => `/attributes/${id}`,
    update: (id: string | number) => `/attributes/${id}`,
    delete: (id: string | number) => `/attributes/${id}`,
    options: '/attribute-options',
    optionById: (id: string | number) => `/attribute-options/${id}`,
    byCategory: (categoryId: string | number) => `/categories/${categoryId}/attributes`,
    categoryAttributeById: (categoryId: string | number, id: string | number) => `/categories/${categoryId}/attributes/${id}`,
  },
  import: {
    brand: '/import/brand',
    category: '/import/category',
    product: '/import/product',
    attributes: '/import/attributes',
    categoryAttributes: '/import/category-attributes',
  },
  export: {
    brand: '/export/brand',
    category: '/export/category',
    product: '/export/product',
    attributes: '/export/attributes',
    categoryAttributes: '/export/category-attributes',
    categoryAttributesImport: '/export/category-attributes/import',
  },
  search: {
    brand: '/search/brand',
  },
} as const;
