export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    sendOtp: '/auth/sendotp',
    sendOtpRegister: '/auth/sendotpregister',
    verifyOtp: '/auth/verifyotp',
    forgotPasswordRequest: '/auth/forgot-password/request',
    forgotPasswordConfirm: '/auth/forgot-password/confirm',
  },
  health: {
    check: '/health-check',
  },
  user: {
    list: '/user',
    create: '/user',
    register: '/user/register',
    update: '/user/update',
    delete: (id: string | number) => `/user/${id}`,
    byId: (id: string | number) => `/user/${id}`,
  },
  role: {
    list: '/role',
    create: '/role',
    byId: (id: string | number) => `/role/${id}`,
    update: (id: string | number) => `/role/${id}`,
    delete: (id: string | number) => `/role/${id}`,
  },
  permission: {
    list: '/permissions',
  },
  brand: {
    list: '/brands',
    create: '/brands',
    update: (id: string | number) => `/brands/update/${id}`,
    byId: (id: string | number) => `/brands/${id}`,
    delete: (id: string | number) => `/brands/${id}`,
    image: (id: string | number) => `/brands/${id}/image`,
    images: (id: string | number) => `/brands/${id}/images`,
    deleteImage: (id: string | number, imageId: string | number) => `/brands/${id}/images/${imageId}`,
    thumbnail: (id: string | number, imageId: string | number) => `/brands/${id}/images/${imageId}/thumbnail`,
  },
  category: {
    list: '/categories',
    tree: '/categories/tree',
    create: '/categories',
    byId: (id: string | number) => `/categories/${id}`,
    bySlug: (slug: string) => `/categories/by-slug/${slug}`,
    deleted: '/categories/deleted',
    update: (id: string | number) => `/categories/${id}`,
    delete: (id: string | number) => `/categories/${id}`,
    deactivate: (id: string | number) => `/categories/${id}/deactivate`,
    status: (id: string | number) => `/categories/${id}/status`,
    move: (id: string | number) => `/categories/${id}/move`,
    reorder: '/categories/reorder',
    merge: '/categories/merge',
    images: (id: string | number) => `/categories/${id}/images`,
    deleteImage: (id: string | number, imageId: string | number) => `/categories/${id}/images/${imageId}`,
    thumbnail: (id: string | number, imageId: string | number) => `/categories/${id}/images/${imageId}/thumbnail`,
  },
  product: {
    list: '/products',
    create: '/products',
    byId: (id: string | number) => `/products/${id}`,
    update: (id: string | number) => `/products/${id}`,
    status: (id: string | number) => `/products/${id}/status`,
    images: (id: string | number) => `/products/${id}/images`,
    deleteImage: (id: string | number, imageId: string | number) => `/products/${id}/images/${imageId}`,
    thumbnail: (id: string | number, imageId: string | number) => `/products/${id}/images/${imageId}/thumbnail`,
  },
  inventory: {
    list: '/admin/inventories',
    byVariantId: (variantId: string | number) => `/admin/inventories/${variantId}`,
    movements: (variantId: string | number) => `/admin/inventories/${variantId}/movements`,
    adjustments: (variantId: string | number) => `/admin/inventories/${variantId}/adjustments`,
  },
  attribute: {
    list: '/attributes',
    create: '/attributes',
    byId: (id: string | number) => `/attributes/${id}`,
    update: (id: string | number) => `/attributes/${id}`,
    delete: (id: string | number) => `/attributes/${id}`,
    options: '/attribute-options',
    optionById: (id: string | number) => `/attribute-options/${id}`,
    byCategory: (categoryId: string | number) => `/categories/${categoryId}/attributes`,
    categoryAttributeById: (categoryId: string | number, id: string | number) => `/categories/${categoryId}/attributes/${id}`,
  },
  import: {
    brand: '/import/brand',
    category: '/import/category',
    product: '/import/product',
    attributes: '/import/attributes',
    categoryAttributes: '/import/category-attributes',
  },
  export: {
    brand: '/export/brand',
    category: '/export/category',
    product: '/export/product',
    attributes: '/export/attributes',
    categoryAttributes: '/export/category-attributes',
    categoryAttributesImport: '/export/category-attributes/import',
  },
  search: {
    brand: '/search/brand',
  },
  cart: {
    my: '/carts/me',
    upsertItem: '/carts/me/items',
    removeItem: (variantId: string | number) => `/carts/me/items/${variantId}`,
    applyVoucher: '/carts/me/voucher/apply',
    removeVoucher: '/carts/me/voucher',
    pricingPreview: '/carts/me/pricing-preview',
    checkout: '/carts/me/checkout',
  },
  order: {
    list: '/orders',
    create: '/orders',
    byId: (id: string | number) => `/orders/${id}`,
    adminStatus: (id: string | number) => `/orders/${id}/admin-status`,
    paymentStatus: (id: string | number) => `/orders/${id}/payment-status`,
    fulfillment: (id: string | number) => `/orders/${id}/fulfillment`,
    myList: '/orders/me',
    myById: (id: string | number) => `/orders/me/${id}`,
    myCancel: (id: string | number) => `/orders/me/${id}/cancel`,
    myReturnRequest: (id: string | number) => `/orders/me/${id}/return-requests`,
  },
} as const;
