export const APP_ROUTES = {
  home: '/home',
  homeProducts: '/home',
  storefrontCategory: (slug: string) => `/home/category/${slug}`,
  storefrontBrand: (slug: string) => `/home/brand/${slug}`,
  dashboard: '/admin/dashboard',
  users: '/admin/management/users',
  roles: '/admin/management/roles',
  brands: '/admin/catalog/brands',
  categories: '/admin/catalog/categories',
  products: '/admin/catalog/products',
  inventory: '/admin/catalog/inventory',
  attributes: '/admin/catalog/attributes',
  operations: '/admin/catalog/operations',
  search: '/admin/catalog/search',
  cart: '/client/cart',
  cartCheckout: '/client/checkout',
  login: '/auth/login',
  myOrders: '/client/orders/me',
  myOrderDetail: (id: string | number) => `/client/orders/me/${id}`,
  adminOrders: '/admin/orders',
  adminOrderDetail: (id: string | number) => `/admin/orders/${id}`,
} as const;
