export const APP_ROUTES = {
  dashboard: '/admin/dashboard',
  users: '/admin/management/users',
  roles: '/admin/management/roles',
  brands: '/admin/catalog/brands',
  categories: '/admin/catalog/categories',
  products: '/admin/catalog/products',
  attributes: '/admin/catalog/attributes',
  operations: '/admin/catalog/operations',
  search: '/admin/catalog/search',
  checkout: '/client/checkout',
  myOrders: '/client/orders/me',
  myOrderDetail: (id: string | number) => `/client/orders/me/${id}`,
  adminOrders: '/admin/orders',
  adminOrderDetail: (id: string | number) => `/admin/orders/${id}`,
} as const;
